[build-system]
requires = [
    "setuptools>=61.0",
    "wheel"
]
build-backend = "setuptools.build_meta"

# https://pypi.org/project/bhad
[project]
name = "bhad"
version = "0.2.6"
description = "Bayesian Histogram-based Anomaly Detection"
requires-python = ">=3.12"
readme = { file = "README.md", content-type = "text/markdown" }

authors = [
  { name = "Alexander Vosseler" }
]
maintainers = [
  { name = "Alexander Vosseler" }
]

keywords = ["bayesian-inference", "anomaly-detection", "unsupervised-learning", "explainability"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

# Note these updated constraints:
dependencies = [
  "pandas>=1.5",
  "scikit-learn>=1.3",
  "matplotlib>=3.0",
  "scipy>=1.9,<1.13",
  "statsmodels>=0.14",
  "tqdm>=4.0",
]

[project.optional-dependencies]
dev = [
  "jupyter",
  "ipykernel",
  "pytest",
  "sphinx",
  "sphinx_rtd_theme",
  "myst-parser",
  "black",
  "isort",
  "mypy",
  "nbsphinx",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["bhad*"]


[project.urls]
homepage = "https://github.com/AVoss84/bhad"
repository = "https://github.com/AVoss84/bhad"
issues = "https://github.com/AVoss84/bhad/issues"

[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = true
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "tests"
]
