name: Publish to Test PyPI

on:
  push:
    tags:
      - "0.2.1"  # v0.2.0, v1.0.0, etc.

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install build twine

      - name: Build the package
        run: |
          python -m build  

      - name: Upload to Test PyPI
        run: |
          twine upload --repository testpypi dist/*
        env:
          TWINE_USERNAME: "__token__"
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
